version: "3.6"
services:
  gin-app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: "gin-app"
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "8888:8888"
    volumes:
      - "conf:/app/conf"
      - "storage:/app/storage"

volumes:
  conf:
    driver: local
  storage:
    driver: local

networks:
  default:
    driver: bridge